base_url_country <- data.frame(
  country = c("china",
              "argentina",
              "australia",
              "belgium - dutch",
              "belgium - french",
              "brazil",
              "canada - english",
              "canada - french",
              "chile",
              "colombia",
              "denmark",
              "germany",
              "spain",
              "france",
              "hong kong",
              "india",
              "ireland",
              "israel",
              "japan",
              "south korea",
              "italy",
              "mexico",
              "netherlands",
              "new zealand",
              "norway",
              "austria",
              "poland",
              "portugal",
              "russia",
              "switzerland - german",
              "singapore",
              "south africa",
              "switzerland - french",
              "sweden",
              "turkey",
              "uae",
              "uk",
              "us"),
  base.url = c("http://cn.indeed.com",
               "http://ar.indeed.com",
               "http://au.indeed.com",
               "http://be.indeed.com",
               "http://emplois.be.indeed.com",
               "http://www.indeed.com.br",
               "http://ca.indeed.com",
               "http://emplois.ca.indeed.com",
               "http://www.indeed.cl",
               "http://co.indeed.com",
               "http://dk.indeed.com",
               "http://de.indeed.com",
               "http://www.indeed.cl",
               "http://www.indeed.fr",
               "http://www.indeed.hk",
               "http://www.indeed.co.in",
               "http://ie.indeed.com",
               "http://il.indeed.com",
               "http://jp.indeed.com",
               "http://kr.indeed.com",
               "http://it.indeed.com",
               "http://www.indeed.co.mx",
               "http://www.indeed.nl",
               "http://nz.indeed.com",
               "http://no.indeed.com",
               "http://at.indeed.com",
               "http://pl.indeed.com",
               "http://www.indeed.pt",
               "http://ru.indeed.com",
               "http://www.indeed.ch",
               "http://www.indeed.com.sg",
               "http://www.indeed.co.za",
               "http://emplois.indeed.ch",
               "http://se.indeed.com",
               "http://tr.indeed.com",
               "http://www.indeed.ae",
               "http://www.indeed.co.uk",
               "http://www.indeed.com"),
  stringsAsFactors = FALSE
)

devtools::use_data(base_url_country, internal = TRUE, overwrite = TRUE)
